# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: hello
    binary: hello
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64

dockers_v2:
  - id: hello
    ids:
      - hello
    images:
      - ghcr.io/renevo/placeholder/hello
    tags:
      - "{{ .Version }}"
    dockerfile: Dockerfile
    platforms:
      - linux/amd64
      - linux/arm64

checksum:
  name_template: checksums.txt

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^art:'
      - '^fonts:'
